name: Build Plugin
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ./src
      - name: Build
        uses: docker://registry.catvibers.me/ittai/builder
        with:
          entrypoint: sh
          args: -c "cd src && pnpm i && ittai --plugin="./" --betterdiscord=../dist --powercordv2=../dist --goosemod=../dist/goosemod --production && rm -rf ./node_modules"
          # rm is a hack to make github actions permissions function
      - name: Prepare to push
        run: |
          sudo chown -R runner:runner ./
          mv ./dist/* .
          rm -r ./dist
          cp ./src/README* . || true
          cp ./src/LICENSE* . || true
          rm -rf ./src
          git init
          git config --local user.email "ittai@catvibers.me"
          git config --local user.name "ittaibot"
          git add ./*
          git commit -m "Build plugin" -a          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: relase
          force: true